sudo: false
language: node_js
branches:
  only:
    - master
node_js: 8
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm install -g codecov
  - codecov
  - npm run semantic-release