sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js: 6
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate