sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js: 8
before_install:
  - npm i -g npm@6.4
install:
  - npm ci
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm install -g codecov
  - codecov
  - npm run semantic-release