sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js: 6
before_install:
  - npm i -g npm@6.4
install:
  - npm ci
  - npm install -g codecov
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
  - codecov